version: "3.8"
services:
  db:
    image: postgres:15
    container_name: benchmarks-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: benchmarks
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d   # scripts iniciais
      - benchmark-data:/var/lib/postgresql/data  # dados persistentes
    networks:
      - benchmark-network

volumes:
  benchmark-data:

networks:
  benchmark-network:


